### ISSUE TITLE
Crossbow's Power enchant is not working properly

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#138]
#### Mod version:

HaCLib Version: HeatAndClimateLib_1.12.2-3.2.3
HaCMod Version: HeatAndClimateMod_1.12.2-3.2.5

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:

![](https://user-images.githubusercontent.com/28519848/72961436-02657080-3dec-11ea-93f1-e302c2ebdbe0.png)

#### How to reproduce:

1. Enchant an HaC crossbow with Power 5 spell.
2. Hold the right mouse button and wait for several seconds, making sure the bow is full-charged.
3. Release the right mouse button, and find that this shoot deals about 10 points of damage, nearly the same as a crossbow without any enchantment could do.
4. Just click the right mouse button quickly with a Power-5-enchanted crossbow in the main hand,
and every click deals 10 points of damage.

I have a screen record for this issue, here is the link:
https://imgur.com/anqKcR6

This issue leads to the fact that Crossbows are able to be enchanted with Power spell indeed, but that enchantment is of no use.
This is a bit weird, and I have no idea about how to deal with this issue.
Hope to get your help.
Look forward your reply!
Thanks in advance!

**Comment by defeatedcrow** [comment]
Hello.
This is a bug, not an intended specification.
The correct specification is that the damage amount is corrected by Power (at a different magnification than the vanilla bow).
Thank you for your report. It should be fixed in the next update!

**Comment by defeatedcrow** [comment]
It fixed at 83768b2bf35db832c48a7314b430fd9742c8dc0a
Thanks for your report!

**Comment by RisingInIris2017** [comment]
> It fixed at [83768b2](https://github.com/defeatedcrow/HeatAndClimateMod/commit/83768b2bf35db832c48a7314b430fd9742c8dc0a)

Thanks for your help! I have updated my HAC mod.
But unfortunately I found that in the latest version 3.2.6, this issue was still existing.
I have a screen record for this:
https://imgur.com/gallery/zDj2UFO

**Comment by defeatedcrow** [comment]
Thank you for the report!
Crossbow damage calculation was incorrect. It has been fixed in v3.2.7.

**Comment by RisingInIris2017** [comment]
Okay I will have a try! Thanks for your effort! :)

**Comment by RisingInIris2017** [comment]
Now this issue is completely fixed. Thanks again you dear Crow-san! ❤️
