### ISSUE TITLE
Block Entity tick crash 1.19.2

### ISSUE THREAD

**Issue by dave75vgnut** [defeatedcrow/HeatAndClimateMod#279]
HaC mineral/ore blocks cause Block Entity Tick crash when using simple quarry mod or create mod tunnel bore creation, may also crash when other mods try to mine HaC mineral/ore blocks.

**Comment by defeatedcrow** [comment]
Thanks for your report!
It fixed at v4-alpha6 ( https://github.com/defeatedcrow/HeatAndClimateMod/releases/tag/v4-alpha6 ).

**Comment by LKD-PIX** [comment]
This is not fixed i am on v4-alpha9, Quarry from RFTools still crashes game
